### ISSUE TITLE
Word 2013: to add a citation change the current page and hide the markups

### ISSUE THREAD

**Issue by Nodragem** [zotero/zotero#885]
Hello,

Everything is in the title I would say: I am using Word 2013 and each time I edit or add a citation, the current page changes to a random page (getting me lost in my document) and the markup display passes from All Markup to No Markup. 

I tried to update Zotero, I have the version: 4.0.28.7
But it says there is no update available, which seems weird to me as the current changelog states there is a version 4.0.28.9.

So I do not know what to do to resolve the problem :/ 
I'm writting a thesis, so to get sent to a random page is quite an hassle, hehe :D !

**Comment by dstillman** [comment]
For support, please post to the Zotero Forums — this tracker is for developer use only.

This issue was fixed in the latest version of the Word integration plugin. [Updates Not Detected](https://www.zotero.org/support/kb/updates_not_detected) may be relevant, but you can always install the latest versions from zotero.org.

**Comment by Nodragem** [comment]
Hi,
Thank for your reply!
I thought it was here that we report bugs, sorry.
Nevertheless, it seems that the new version of the Word plug-in (with a ZOTERO tab in the ribbon) does not fix the bug.
Furthermore the last version of Zotero to download on zotero.org is the version 4.0.28.7 and not the version 4.0.28.9 :/

I am going to post on the forum.

Thank you again!

**Comment by dstillman** [comment]
Oh, sorry, if you're on Standalone, the fix for this hasn't yet been pushed out. We'll try to get that out shortly, but for an immediate fix, you can install the word processor plugin linked from the download page (which is normally for Firefox) into Standalone using the Add-ons window.
